from django.core.management.base import BaseCommand
from django.utils.text import slugify
from src.professionals.models import TradeCategory, TradeSubCategory


class Command(BaseCommand):
    help = 'Seed trade categories and subcategories'

    def handle(self, *args, **options):
        trades = [
            {
                'name': 'Electrician',
                'icon': 'lucide:zap',
                'description': 'Installations, rewires, and safety work.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Consumer Unit / Fuse Board Replacement',
                    'Electrical Inspection & Testing',
                    'Socket & Switch Installation',
                    'Lighting Installation',
                    'EV Charger Installation',
                    'Rewiring',
                    'Outdoor & Garden Lighting',
                    'Security Lighting',
                    'Smart Home Wiring',
                    'Fault Finding & Repairs',
                    'Emergency Lighting',
                    'Data & TV Points',
                ],
            },
            {
                'name': 'Plumber',
                'icon': 'lucide:wrench',
                'description': 'Leaks, fittings, boilers, and repairs.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Boiler Installation',
                    'Boiler Repair & Servicing',
                    'Leak Detection & Repair',
                    'Bathroom Installation',
                    'Radiator Installation & Repair',
                    'Pipe Fitting & Replacement',
                    'Tap & Toilet Repair',
                    'Underfloor Heating',
                    'Water Softener Installation',
                    'Drain Unblocking',
                    'Hot Water Cylinder Installation',
                    'Emergency Plumbing',
                ],
            },
            {
                'name': 'Gas Engineer',
                'icon': 'lucide:flame',
                'description': 'Gas safety, servicing, and maintenance.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Boiler Installation',
                    'Boiler Service',
                    'Gas Safety Certificate',
                    'Boiler Repair',
                    'Central Heating Installation',
                    'Gas Cooker Installation',
                    'Gas Fire Installation',
                    'Landlord Gas Safety Check',
                    'Pressure & Leak Testing',
                    'Flue Installation',
                    'Smart Thermostat Installation',
                ],
            },
            {
                'name': 'Builder',
                'icon': 'lucide:hammer',
                'description': 'General building, extensions, and repairs.',
                'requires_coverage_area': True,
                'subcategories': [
                    'House Extensions',
                    'Loft Conversions',
                    'Garage Conversions',
                    'Basement Conversions',
                    'New Build',
                    'Structural Repairs',
                    'Underpinning',
                    'Brickwork & Pointing',
                    'Concrete Work',
                    'Partition Walls',
                    'Demolition',
                    'Groundwork & Foundations',
                    'Porch Construction',
                ],
            },
            {
                'name': 'Roofer',
                'icon': 'lucide:house',
                'description': 'Roof repairs, installations, and inspections.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Roof Repairs',
                    'Roof Replacement',
                    'Flat Roof Installation',
                    'Felt Roofing',
                    'EPDM Rubber Roofing',
                    'Guttering & Fascias',
                    'Chimney Repairs',
                    'Skylight Installation',
                    'Lead Flashing',
                    'Roof Inspection',
                    'Moss & Algae Removal',
                    'Tile & Slate Replacement',
                ],
            },
            {
                'name': 'Painter & Decorator',
                'icon': 'lucide:paintbrush-2',
                'description': 'Interior and exterior decorating work.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Interior Painting',
                    'Exterior Painting',
                    'Wallpaper Hanging',
                    'Wallpaper Removal',
                    'Wood Staining & Varnishing',
                    'Coving & Cornice',
                    'Plastering & Skimming',
                    'Spray Painting',
                    'Damp Proofing & Treatment',
                    'Artex Removal',
                    'Feature Walls',
                    'Commercial Decorating',
                ],
            },
            {
                'name': 'Carpenter',
                'icon': 'lucide:ruler',
                'description': 'Joinery, fitted work, and wood repairs.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Door Fitting & Hanging',
                    'Skirting & Architrave',
                    'Staircase Installation',
                    'Fitted Wardrobes',
                    'Kitchen Fitting',
                    'Decking Installation',
                    'Flooring Installation',
                    'Loft Boarding',
                    'Window Fitting',
                    'Bespoke Furniture',
                    'Fence Installation',
                    'Shed Assembly',
                    'Structural Timber Work',
                ],
            },
            {
                'name': 'Gardener',
                'icon': 'lucide:trees',
                'description': 'Garden care, tidy-ups, and landscaping.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Lawn Mowing & Maintenance',
                    'Garden Design',
                    'Hedge Trimming',
                    'Tree Surgery',
                    'Patio & Path Laying',
                    'Planting & Borders',
                    'Weed Control',
                    'Irrigation Systems',
                    'Turfing',
                    'Garden Clearance',
                    'Pond Installation',
                    'Artificial Grass',
                    'Fencing & Gates',
                ],
            },
            {
                'name': 'Cleaner',
                'icon': 'lucide:sparkles',
                'description': 'Domestic and commercial cleaning services.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Regular Domestic Cleaning',
                    'End of Tenancy Cleaning',
                    'Deep Cleaning',
                    'Carpet Cleaning',
                    'Upholstery Cleaning',
                    'Window Cleaning',
                    'Oven Cleaning',
                    'Office Cleaning',
                    'After Build Cleaning',
                    'Pressure Washing',
                    'Gutter Cleaning',
                    'Move In / Move Out Cleaning',
                ],
            },
            {
                'name': 'Handyman',
                'icon': 'lucide:drill',
                'description': 'Odd jobs, fixes, and home maintenance.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Flat Pack Assembly',
                    'Picture & Mirror Hanging',
                    'TV Wall Mounting',
                    'Shelf Installation',
                    'Door & Lock Repairs',
                    'Tile Repairs',
                    'Grouting & Silicone',
                    'Minor Plumbing Repairs',
                    'Draught Proofing',
                    'Gutter Repairs',
                    'Odd Jobs',
                    'Curtain & Blind Fitting',
                    'Fence Repairs',
                ],
            },
            {
                'name': 'Locksmith',
                'icon': 'lucide:key-round',
                'description': 'Lock changes, emergencies, and access control.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Emergency Lockout',
                    'Lock Replacement',
                    'Lock Repair',
                    'Key Cutting',
                    'Deadlock Installation',
                    'UPVC Door Lock Repair',
                    'Window Lock Installation',
                    'Safe Opening & Installation',
                    'Access Control Systems',
                    'Master Key Systems',
                    'Security Assessment',
                ],
            },
            {
                'name': 'Bathroom Fitter',
                'icon': 'lucide:shower-head',
                'description': 'Bathroom refurbishments and installations.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Full Bathroom Installation',
                    'Shower Installation',
                    'Bath Installation',
                    'Toilet Installation',
                    'Basin & Vanity Unit',
                    'Tiling',
                    'Wet Room Installation',
                    'En-Suite Installation',
                    'Bathroom Refurbishment',
                    'Underfloor Heating',
                    'Extractor Fan Installation',
                    'Disabled Bathroom Adaptations',
                ],
            },
            {
                'name': 'Kitchen Fitter',
                'icon': 'lucide:chef-hat',
                'description': 'Kitchen installations and upgrades.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Full Kitchen Installation',
                    'Kitchen Refurbishment',
                    'Worktop Replacement',
                    'Cabinet Installation',
                    'Appliance Installation',
                    'Splashback Tiling',
                    'Kitchen Lighting',
                    'Sink & Tap Installation',
                    'Extractor Hood Fitting',
                    'Soft Close Hinges & Drawers',
                    'Kitchen Design & Planning',
                    'Handleless Kitchen Fitting',
                ],
            },
            {
                'name': 'Heating Engineer',
                'icon': 'lucide:heater',
                'description': 'Heating systems, boilers, and servicing.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Central Heating Installation',
                    'Boiler Replacement',
                    'Boiler Service & Repair',
                    'Radiator Installation',
                    'Underfloor Heating',
                    'Heat Pump Installation',
                    'Thermostat Installation',
                    'Power Flushing',
                    'Heating System Upgrade',
                    'Annual Service Contract',
                    'Landlord Heating Certificate',
                    'Smart Heating Controls',
                ],
            },
            {
                'name': 'Pest Control',
                'icon': 'lucide:bug',
                'description': 'Inspection, treatment, and prevention plans.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Rat & Mice Control',
                    'Wasp Nest Removal',
                    'Bed Bug Treatment',
                    'Cockroach Treatment',
                    'Ant Control',
                    'Flea Treatment',
                    'Squirrel Control',
                    'Bird Proofing',
                    'Moth Treatment',
                    'Fox Control',
                    'Commercial Pest Control',
                    'Pest Inspection & Survey',
                ],
            },
            {
                'name': 'Tiler',
                'icon': 'lucide:grid-2x2',
                'description': 'Wall, floor, kitchen, and bathroom tiling.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Bathroom Wall Tiling',
                    'Floor Tiling',
                    'Kitchen Splashback Tiling',
                    'Outdoor Tiling',
                    'Tile Removal & Replacement',
                    'Mosaic Tiling',
                    'Large Format Tiling',
                    'Wet Room Tiling',
                    'Grout Repair & Regrouting',
                    'Underfloor Heating with Tiling',
                    'Commercial Tiling',
                    'Tile Cutting & Shaping',
                ],
            },
            {
                'name': 'Plasterer',
                'icon': 'lucide:paint-roller',
                'description': 'Skimming, rendering, and surface prep.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Skim Coating',
                    'Full Room Plastering',
                    'Rendering',
                    'Dry Lining',
                    'Coving Installation',
                    'Artex Removal',
                    'Patch Plastering',
                    'Ceiling Plastering',
                    'External Rendering',
                    'Insulated Render',
                    'Pebble Dash',
                    'Plasterboard Installation',
                ],
            },
            {
                'name': 'Flooring Specialist',
                'icon': 'lucide:layout-panel-top',
                'description': 'Wood, laminate, vinyl, and repairs.',
                'requires_coverage_area': True,
                'subcategories': [
                    'Hardwood Floor Installation',
                    'Laminate Flooring',
                    'Vinyl & LVT Flooring',
                    'Carpet Fitting',
                    'Floor Sanding & Finishing',
                    'Underfloor Heating Installation',
                    'Tile Flooring',
                    'Engineered Wood Flooring',
                    'Floor Levelling',
                    'Subfloor Preparation',
                    'Floor Repairs',
                    'Commercial Flooring',
                ],
            },
        ]

        for i, trade_data in enumerate(trades):
            trade, created = TradeCategory.objects.get_or_create(
                slug=slugify(trade_data['name']),
                defaults={
                    'name': trade_data['name'],
                    'icon': trade_data['icon'],
                    'description': trade_data['description'],
                    'requires_coverage_area': trade_data['requires_coverage_area'],
                    'sort_order': i,
                }
            )
            if not created:
                # Update icon and description on existing records
                updated = False
                if trade.icon != trade_data['icon']:
                    trade.icon = trade_data['icon']
                    updated = True
                if trade.description != trade_data['description']:
                    trade.description = trade_data['description']
                    updated = True
                if updated:
                    trade.save()
                self.stdout.write(f'Trade already exists: {trade.name}')
            else:
                self.stdout.write(self.style.SUCCESS(f'Created trade: {trade.name}'))

            for j, sub_name in enumerate(trade_data['subcategories']):
                _, sub_created = TradeSubCategory.objects.get_or_create(
                    trade_category=trade,
                    slug=slugify(sub_name),
                    defaults={'name': sub_name, 'sort_order': j}
                )
                if sub_created:
                    self.stdout.write(self.style.SUCCESS(f'  + {sub_name}'))
