# Generated by Django 3.2.12 on 2026-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210317_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professional', 'Professional'), ('client', 'Client')], default='admin', max_length=20),
        ),
    ]
