# Generated by Django 3.2.12 on 2026-05-04 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='trade_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('requires_coverage_area', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Category',
                'verbose_name_plural': 'Trade Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TradeSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='professionals.tradecategory')),
            ],
            options={
                'verbose_name': 'Trade Subcategory',
                'verbose_name_plural': 'Trade Subcategories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('trade_category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('SELF_EMPLOYED', 'Self Employed'), ('LIMITED_COMPANY', 'Limited Company'), ('STARTING_BUSINESS', 'Starting Business')], max_length=20)),
                ('number_of_employees', models.CharField(choices=[('ONE', '1'), ('TWO_TO_FIVE', '2-5'), ('SIX_TO_NINE', '6-9'), ('TEN_PLUS', '10+')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('town_city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_categories', models.ManyToManyField(blank=True, related_name='professionals', to='professionals.TradeSubCategory')),
                ('trade_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.tradecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Professional Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCoverageArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_postcode', models.CharField(blank=True, max_length=10)),
                ('radius_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('postcode_district', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('RADIUS', 'Radius'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_areas', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'Professional Coverage Area',
                'verbose_name_plural': 'Professional Coverage Areas',
                'unique_together': {('professional', 'postcode_district')},
            },
        ),
    ]
