# Generated by Django 3.2.12 on 2026-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
